//! Wire-shape contract: the platform's OpenAPI schemas against this SDK's
//! serde types.
//!
//! The platform's `docs/api` specs are the authoritative wire contract. A
//! schema-only snapshot of them is committed under `testdata/openapi/`,
//! derived by `scripts/snapshot_openapi_schemas.py` at the platform commit its
//! file headers name (see `testdata/openapi/README.md`).
//!
//! The contract reads every schema that declares properties from the snapshot,
//! and every public struct in `src/` that derives `Serialize` or `Deserialize`
//! with its wire field names (`#[serde(rename = "...")]`, else the field name).
//! For every struct whose name matches a schema, it compares the two field sets.
//!
//! Known drift is recorded in `testdata/wire_shape_baseline.json`, and the tests
//! fail on any difference from it, in either direction: new drift, drift that
//! has been burned down but is still recorded, a type that no longer matches a
//! schema, or a schema whose declarations across spec files changed. The
//! baseline is pinned to the platform commit the snapshot's headers name.
//!
//! After a deliberate change, regenerate the baseline with:
//!
//! ```text
//! WIRE_SHAPE_REFRESH=1 cargo test --test wire_shape_contract -- --ignored refresh_baseline
//! ```
//!
//! It takes the platform commit from the snapshot's headers; there is no other
//! source for it. Never regenerate to silence a failure: read it first.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use syn::ext::IdentExt;

/// The first line `scripts/snapshot_openapi_schemas.py` writes in every file.
const HEADER_FIRST_LINE: &str = "# GENERATED by scripts/snapshot_openapi_schemas.py - do not edit.";
const REFRESH_ENV: &str = "WIRE_SHAPE_REFRESH";

type Fields = Vec<String>;

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn snapshot_dir() -> PathBuf {
    root().join("testdata").join("openapi")
}

fn baseline_path() -> PathBuf {
    root().join("testdata").join("wire_shape_baseline.json")
}

fn snapshot_files(dir: &Path) -> Vec<(String, String)> {
    let mut files: Vec<(String, String)> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("{}: {e}", dir.display()))
        .map(|entry| entry.expect("a directory entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "yaml"))
        .map(|path| {
            let name = path
                .file_name()
                .expect("a file name")
                .to_string_lossy()
                .into_owned();
            let text = fs::read_to_string(&path).unwrap_or_else(|e| panic!("{name}: {e}"));
            (name, text)
        })
        .collect();
    files.sort();
    assert!(!files.is_empty(), "{} holds no *.yaml", dir.display());
    files
}

// ---------------------------------------------------------------------------
// The spec side
// ---------------------------------------------------------------------------

/// A key as the snapshot writes it: a JSON string.
fn key(token: &str) -> Result<String, String> {
    serde_json::from_str::<String>(token).map_err(|e| format!("{token}: not a JSON string: {e}"))
}

/// The schema declarations of one snapshot file, in order: each name with its
/// property names, or `None` for a declaration without properties.
///
/// It reads exactly the form `render()` in `scripts/snapshot_openapi_schemas.py`
/// writes, and refuses any other line. The workflow's `--check-snapshot` holds
/// the committed files to that form, so a refusal here means the reader and the
/// script disagree about it.
fn declarations(text: &str) -> Result<Vec<(String, Option<Fields>)>, String> {
    let mut out = Vec::new();
    let mut lines = text
        .lines()
        .filter(|line| !line.starts_with('#'))
        .peekable();
    if lines.next() != Some("components:") {
        return Err("expected `components:`".into());
    }
    match lines.next() {
        Some("  schemas: {}") => {
            return match lines.next() {
                None => Ok(out),
                Some(extra) => Err(format!("unexpected line after `schemas: {{}}`: {extra:?}")),
            };
        }
        Some("  schemas:") => {}
        other => return Err(format!("expected `  schemas:`, found {other:?}")),
    }
    while let Some(line) = lines.next() {
        let rest = line
            .strip_prefix("    ")
            .filter(|rest| !rest.starts_with(' '))
            .ok_or_else(|| format!("unexpected line {line:?}"))?;
        if let Some(name) = rest.strip_suffix(": {}") {
            out.push((key(name)?, None));
        } else if let Some(name) = rest.strip_suffix(':') {
            if lines.next() != Some("      properties:") {
                return Err(format!("{name}: expected `      properties:`"));
            }
            let mut fields = Vec::new();
            while let Some(field) = lines
                .peek()
                .copied()
                .and_then(|l| l.strip_prefix("        "))
            {
                let field = field
                    .strip_suffix(": {}")
                    .ok_or_else(|| format!("unexpected property line {field:?}"))?;
                fields.push(key(field)?);
                lines.next();
            }
            if fields.is_empty() {
                return Err(format!("{name}: `properties:` without a property"));
            }
            out.push((key(name)?, Some(fields)));
        } else {
            return Err(format!("unexpected line {line:?}"));
        }
    }
    Ok(out)
}

/// The spec side of the contract: every schema that declares properties.
struct Spec {
    /// Each schema's sorted property names. On a name declared in several
    /// files, the last file in name order wins.
    merged: BTreeMap<String, Fields>,
    /// Every schema declared in more than one file with DIFFERENT property
    /// sets, keyed by file. Identical redeclarations are benign.
    cross_spec: BTreeMap<String, BTreeMap<String, Fields>>,
}

fn load_spec(files: &[(String, String)]) -> Spec {
    let mut merged = BTreeMap::new();
    let mut all: BTreeMap<String, BTreeMap<String, Fields>> = BTreeMap::new();
    for (file, text) in files {
        // A later declaration of a name in one file replaces an earlier one,
        // as a YAML loader reads a repeated key.
        let mut in_file: BTreeMap<String, Option<Fields>> = BTreeMap::new();
        for (name, fields) in declarations(text).unwrap_or_else(|e| panic!("{file}: {e}")) {
            in_file.insert(name, fields);
        }
        for (name, fields) in in_file {
            let Some(mut fields) = fields else { continue };
            fields.sort();
            fields.dedup();
            all.entry(name.clone())
                .or_default()
                .insert(file.clone(), fields.clone());
            merged.insert(name, fields);
        }
    }
    let cross_spec = all
        .into_iter()
        .filter(|(_, decls)| decls.values().collect::<BTreeSet<_>>().len() > 1)
        .collect();
    Spec { merged, cross_spec }
}

/// The full platform commit every snapshot file's header names.
///
/// Each file must carry the generated header, name its own source file, and
/// name the same full 40-character commit as every other file: the same rule
/// as `snapshot_commit` in the vendored script.
fn snapshot_commit(files: &[(String, String)]) -> Result<String, String> {
    let mut commits = BTreeMap::new();
    for (file, text) in files {
        let mut lines = text.lines();
        if lines.next() != Some(HEADER_FIRST_LINE) {
            return Err(format!("{file}: missing the generated header"));
        }
        let source = lines.next().unwrap_or_default();
        let commit = source
            .strip_prefix("# Source: docs/api/")
            .and_then(|rest| rest.strip_prefix(file.as_str()))
            .and_then(|rest| rest.strip_prefix(" at platform commit "))
            .filter(|c| c.len() == 40 && c.bytes().all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f')))
            .ok_or_else(|| {
                format!("{file}: the header does not name this file's source and a full platform commit: {source:?}")
            })?;
        commits.insert(file.clone(), commit.to_owned());
    }
    let named: BTreeSet<&String> = commits.values().collect();
    match named.into_iter().collect::<Vec<_>>().as_slice() {
        [one] => Ok((*one).clone()),
        many => Err(format!(
            "the snapshot's files name {} platform commits: {commits:?}",
            many.len()
        )),
    }
}

// ---------------------------------------------------------------------------
// The SDK side
// ---------------------------------------------------------------------------

/// What a field's `#[serde(...)]` attributes say about its wire name.
#[derive(Default)]
struct FieldSerde {
    rename: Option<String>,
    skip: bool,
    flatten: bool,
}

fn field_serde(attrs: &[syn::Attribute]) -> syn::Result<FieldSerde> {
    let mut out = FieldSerde::default();
    for attr in attrs.iter().filter(|a| a.path().is_ident("serde")) {
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("rename") {
                if !meta.input.peek(syn::Token![=]) {
                    return Err(meta.error(
                        "rename(...) with separate serialize and deserialize names is not supported by this contract",
                    ));
                }
                out.rename = Some(meta.value()?.parse::<syn::LitStr>()?.value());
            } else if meta.path.is_ident("skip") {
                out.skip = true;
            } else if meta.path.is_ident("flatten") {
                out.flatten = true;
            } else if meta.input.peek(syn::Token![=]) {
                // alias, default = "...", skip_serializing_if, with, ...: none
                // changes the name a field is written under.
                meta.value()?.parse::<syn::Expr>()?;
            } else if meta.input.peek(syn::token::Paren) {
                meta.parse_nested_meta(|nested| {
                    if nested.input.peek(syn::Token![=]) {
                        nested.value()?.parse::<syn::Expr>()?;
                    }
                    Ok(())
                })?;
            }
            Ok(())
        })?;
    }
    Ok(out)
}

fn derives_serde(attrs: &[syn::Attribute]) -> syn::Result<bool> {
    let mut found = false;
    for attr in attrs.iter().filter(|a| a.path().is_ident("derive")) {
        attr.parse_nested_meta(|meta| {
            let last = meta.path.segments.last().map(|s| s.ident.to_string());
            if matches!(last.as_deref(), Some("Serialize" | "Deserialize")) {
                found = true;
            }
            Ok(())
        })?;
    }
    Ok(found)
}

/// The container attributes that change the wire names of a struct's fields,
/// which this contract refuses rather than guesses at.
fn refuse_container_serde(item: &syn::ItemStruct) -> Result<(), String> {
    for attr in item.attrs.iter().filter(|a| a.path().is_ident("serde")) {
        let mut refused = None;
        attr.parse_nested_meta(|meta| {
            for name in ["rename_all", "rename_all_fields", "tag", "transparent"] {
                if meta.path.is_ident(name) {
                    refused = Some(name);
                }
            }
            if meta.input.peek(syn::Token![=]) {
                meta.value()?.parse::<syn::Expr>()?;
            } else if meta.input.peek(syn::token::Paren) {
                meta.parse_nested_meta(|nested| {
                    if nested.input.peek(syn::Token![=]) {
                        nested.value()?.parse::<syn::Expr>()?;
                    }
                    Ok(())
                })?;
            }
            Ok(())
        })
        .map_err(|e| format!("{}: {e}", item.ident))?;
        if let Some(name) = refused {
            return Err(format!(
                "{}: #[serde({name})] changes its fields' wire names, which this contract does not model",
                item.ident
            ));
        }
    }
    Ok(())
}

/// The wire field names of a public struct that derives `Serialize` or
/// `Deserialize`, sorted; `None` for any other item.
fn wire_fields(item: &syn::ItemStruct) -> Result<Option<Fields>, String> {
    let derives = derives_serde(&item.attrs).map_err(|e| format!("{}: {e}", item.ident))?;
    if !matches!(item.vis, syn::Visibility::Public(_)) || !derives {
        return Ok(None);
    }
    let syn::Fields::Named(named) = &item.fields else {
        return Ok(None);
    };
    refuse_container_serde(item)?;
    let mut fields = Vec::new();
    for field in &named.named {
        let ident = field
            .ident
            .as_ref()
            .expect("a named field")
            .unraw()
            .to_string();
        let serde =
            field_serde(&field.attrs).map_err(|e| format!("{}.{ident}: {e}", item.ident))?;
        if serde.flatten {
            return Err(format!(
                "{}.{ident}: #[serde(flatten)] hides the wire names this contract compares",
                item.ident
            ));
        }
        if !serde.skip {
            fields.push(serde.rename.unwrap_or(ident));
        }
    }
    fields.sort();
    fields.dedup();
    Ok(Some(fields))
}

fn collect_structs(items: &[syn::Item], out: &mut Vec<(String, Fields)>) -> Result<(), String> {
    for item in items {
        match item {
            syn::Item::Struct(item) => {
                if let Some(fields) = wire_fields(item)? {
                    out.push((item.ident.to_string(), fields));
                }
            }
            syn::Item::Mod(module) => {
                if let Some((_, items)) = &module.content {
                    collect_structs(items, out)?;
                }
            }
            _ => {}
        }
    }
    Ok(())
}

fn rust_sources(dir: &Path, out: &mut Vec<PathBuf>) {
    for entry in fs::read_dir(dir).unwrap_or_else(|e| panic!("{}: {e}", dir.display())) {
        let path = entry.expect("a directory entry").path();
        if path.is_dir() {
            rust_sources(&path, out);
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            out.push(path);
        }
    }
}

/// Every public serde struct in `src/`, by name, with its wire field names.
fn sdk_types() -> BTreeMap<String, Fields> {
    let mut paths = Vec::new();
    rust_sources(&root().join("src"), &mut paths);
    paths.sort();
    let mut out: BTreeMap<String, Fields> = BTreeMap::new();
    for path in paths {
        let text = fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        let file = syn::parse_file(&text).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        let mut found = Vec::new();
        collect_structs(&file.items, &mut found)
            .unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        for (name, fields) in found {
            if let Some(previous) = out.get(&name) {
                // Two structs of one name would make a match ambiguous.
                assert_eq!(
                    previous,
                    &fields,
                    "{name} is declared twice in src/ with different wire fields ({})",
                    path.display()
                );
            }
            out.insert(name, fields);
        }
    }
    out
}

// ---------------------------------------------------------------------------
// The contract
// ---------------------------------------------------------------------------

#[derive(Deserialize, serde::Serialize, Debug, PartialEq, Eq, Clone)]
struct Drift {
    sdk_only: Fields,
    spec_only: Fields,
}

#[derive(Deserialize)]
struct Baseline {
    openapi_specs_sha: String,
    cross_spec_duplicates: BTreeMap<String, BTreeMap<String, Fields>>,
    registered_types: Vec<String>,
    per_type_drift: BTreeMap<String, Drift>,
}

struct Observed {
    commit: String,
    spec: Spec,
    registered: Vec<String>,
    drift: BTreeMap<String, Drift>,
}

fn difference(a: &[String], b: &[String]) -> Fields {
    let b: BTreeSet<&String> = b.iter().collect();
    a.iter().filter(|x| !b.contains(x)).cloned().collect()
}

fn observe() -> Observed {
    let files = snapshot_files(&snapshot_dir());
    let commit = snapshot_commit(&files).unwrap_or_else(|e| panic!("{e}"));
    let spec = load_spec(&files);
    let sdk = sdk_types();
    let mut registered = Vec::new();
    let mut drift = BTreeMap::new();
    for (name, sdk_fields) in &sdk {
        let Some(spec_fields) = spec.merged.get(name) else {
            continue;
        };
        registered.push(name.clone());
        let entry = Drift {
            sdk_only: difference(sdk_fields, spec_fields),
            spec_only: difference(spec_fields, sdk_fields),
        };
        if !entry.sdk_only.is_empty() || !entry.spec_only.is_empty() {
            drift.insert(name.clone(), entry);
        }
    }
    Observed {
        commit,
        spec,
        registered,
        drift,
    }
}

fn baseline() -> Baseline {
    let path = baseline_path();
    let text = fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

const REGENERATE: &str =
    "Regenerate the baseline only for a deliberate change: see the header of tests/wire_shape_contract.rs.";

#[test]
fn the_baseline_is_pinned_to_the_snapshots_platform_commit() {
    // A baseline pinned to any other commit, such as this repository's own
    // HEAD, would name a spec the contract never read.
    let observed = observe();
    assert_eq!(
        baseline().openapi_specs_sha,
        observed.commit,
        "the baseline's openapi_specs_sha is not the commit the snapshot's headers name. {REGENERATE}"
    );
}

#[test]
fn both_sides_are_read() {
    // A reader that silently read nothing would make every other test pass.
    let observed = observe();
    assert!(
        observed.spec.merged.len() > 100,
        "only {} schemas read from the snapshot",
        observed.spec.merged.len()
    );
    assert!(
        observed
            .registered
            .iter()
            .any(|name| name == "DecideResponse"),
        "DecideResponse, a type the SDK and the spec both declare, did not match"
    );
}

#[test]
fn no_drift_outside_the_baseline() {
    let observed = observe();
    let recorded = baseline().per_type_drift;
    let mut problems = Vec::new();
    for (name, drift) in &observed.drift {
        match recorded.get(name) {
            None => problems.push(format!("  {name}: NEW drift {drift:?}")),
            Some(entry) if entry != drift => {
                problems.push(format!(
                    "  {name}: drift changed from {entry:?} to {drift:?}"
                ));
            }
            Some(_) => {}
        }
    }
    for name in recorded
        .keys()
        .filter(|name| !observed.drift.contains_key(*name))
    {
        problems.push(format!(
            "  {name}: recorded drift no longer observed; remove it so a reintroduction is caught"
        ));
    }
    assert!(
        problems.is_empty(),
        "wire-shape drift differs from the baseline:\n{}\n{REGENERATE}",
        problems.join("\n")
    );
}

#[test]
fn the_matched_types_are_the_recorded_ones() {
    // A type disappearing from either side must be a deliberate, reviewed change.
    let observed = observe();
    let recorded = baseline().registered_types;
    assert_eq!(
        observed.registered,
        recorded,
        "added: {:?}; no longer matching: {:?}. {REGENERATE}",
        difference(&observed.registered, &recorded),
        difference(&recorded, &observed.registered)
    );
}

#[test]
fn cross_spec_divergence_is_the_recorded_one() {
    let observed = observe();
    assert_eq!(
        observed.spec.cross_spec,
        baseline().cross_spec_duplicates,
        "a schema declared in several spec files diverges differently from the baseline. {REGENERATE}"
    );
}

#[test]
#[ignore = "rewrites testdata/wire_shape_baseline.json; run with WIRE_SHAPE_REFRESH=1"]
fn refresh_baseline() {
    assert_eq!(
        std::env::var(REFRESH_ENV).as_deref(),
        Ok("1"),
        "set {REFRESH_ENV}=1 to rewrite testdata/wire_shape_baseline.json"
    );
    let observed = observe();
    let baseline = serde_json::json!({
        "_comment": "Known wire-shape drift between the Rust SDK's serde types and the platform's OpenAPI schemas, pinned to the platform commit the snapshot's headers name. Generated by the ignored refresh_baseline test in tests/wire_shape_contract.rs; the tests fail on any difference from it. Burn entries down over time.",
        "openapi_specs_sha": observed.commit,
        "cross_spec_duplicates": observed.spec.cross_spec,
        "registered_types": observed.registered,
        "per_type_drift": observed.drift,
    });
    let text = serde_json::to_string_pretty(&baseline).expect("the baseline serializes") + "\n";
    fs::write(baseline_path(), text).expect("the baseline is written");
}

// ---------------------------------------------------------------------------
// The readers, held to the forms they claim to read
// ---------------------------------------------------------------------------

const SNAPSHOT_HEADER: &str = "# GENERATED by scripts/snapshot_openapi_schemas.py - do not edit.\n\
     # Source: docs/api/a-api.yaml at platform commit 0123456789abcdef0123456789abcdef01234567\n";

#[test]
fn the_snapshot_reader_keeps_the_last_declaration_and_skips_ones_without_properties() {
    let text = "components:\n  schemas:\n    \"Twice\":\n      properties:\n        \"first\": {}\n    \
                \"Bare\": {}\n    \"Twice\":\n      properties:\n        \"second\": {}\n        \"a b\": {}\n";
    let spec = load_spec(&[("a-api.yaml".into(), text.into())]);
    assert_eq!(
        spec.merged.get("Twice"),
        Some(&vec!["a b".to_string(), "second".to_string()])
    );
    assert!(!spec.merged.contains_key("Bare"));
}

#[test]
fn the_snapshot_reader_records_only_differing_declarations_across_files() {
    let one = "components:\n  schemas:\n    \"Same\":\n      properties:\n        \"x\": {}\n    \
               \"Split\":\n      properties:\n        \"x\": {}\n";
    let two = "components:\n  schemas:\n    \"Same\":\n      properties:\n        \"x\": {}\n    \
               \"Split\":\n      properties:\n        \"y\": {}\n";
    let spec = load_spec(&[("a.yaml".into(), one.into()), ("b.yaml".into(), two.into())]);
    assert_eq!(spec.cross_spec.keys().collect::<Vec<_>>(), vec!["Split"]);
    assert_eq!(
        spec.merged.get("Split"),
        Some(&vec!["y".to_string()]),
        "the last file wins"
    );
}

#[test]
fn the_snapshot_reader_refuses_any_other_form() {
    for text in [
        "openapi: 3.0.0\n",
        "components:\n  schemas:\n    Unquoted:\n      properties:\n        \"x\": {}\n",
        "components:\n  schemas:\n    \"A\":\n      properties:\n        \"x\": {type: string}\n",
        "components:\n  schemas:\n    \"A\":\n      description: prose\n",
        "components:\n  schemas:\n    \"A\":\n      properties:\n",
    ] {
        assert!(declarations(text).is_err(), "accepted {text:?}");
    }
}

#[test]
fn the_header_rule_refuses_what_the_vendored_script_refuses() {
    let body = "components:\n  schemas: {}\n";
    let good = format!("{SNAPSHOT_HEADER}{body}");
    assert_eq!(
        snapshot_commit(&[("a-api.yaml".into(), good.clone())]),
        Ok("0123456789abcdef0123456789abcdef01234567".to_string())
    );
    let other = good.replace("0123456789abcdef", "fedcba9876543210");
    assert!(snapshot_commit(&[
        ("a-api.yaml".into(), good.clone()),
        ("b-api.yaml".into(), other.replace("a-api", "b-api"))
    ])
    .unwrap_err()
    .contains("2 platform commits"));
    assert!(
        snapshot_commit(&[("renamed.yaml".into(), good.clone())]).is_err(),
        "a header naming another file"
    );
    assert!(
        snapshot_commit(&[("a-api.yaml".into(), good.replace("01234567\n", "\n"))]).is_err(),
        "an abbreviated commit"
    );
    assert!(
        snapshot_commit(&[("a-api.yaml".into(), body.to_string())]).is_err(),
        "no header"
    );
}

fn struct_fields(source: &str) -> Result<Option<Fields>, String> {
    let item: syn::ItemStruct = syn::parse_str(source).expect("a struct");
    wire_fields(&item)
}

#[test]
fn the_extractor_reads_renames_and_raw_identifiers() {
    let fields = struct_fields(
        "#[derive(serde::Serialize, Deserialize)] pub struct T {
            #[serde(rename = \"policy_id\")] pub id: String,
            #[serde(skip_serializing_if = \"Option::is_none\", default, alias = \"kind\")] pub r#type: Option<String>,
            #[serde(skip)] pub cached: u8,
        }",
    );
    assert_eq!(
        fields,
        Ok(Some(vec!["policy_id".to_string(), "type".to_string()]))
    );
}

#[test]
fn the_extractor_ignores_what_is_not_a_public_serde_struct() {
    assert_eq!(struct_fields("pub struct T { pub a: u8 }"), Ok(None));
    assert_eq!(
        struct_fields("#[derive(Serialize)] struct T { a: u8 }"),
        Ok(None)
    );
    assert_eq!(
        struct_fields("#[derive(Deserialize)] pub struct T(pub u8);"),
        Ok(None)
    );
}

#[test]
fn the_extractor_refuses_what_it_cannot_see() {
    for source in [
        "#[derive(Serialize)] pub struct T { #[serde(flatten)] pub inner: Inner }",
        "#[derive(Serialize)] #[serde(rename_all = \"camelCase\")] pub struct T { pub a: u8 }",
        "#[derive(Serialize)] #[serde(tag = \"kind\")] pub struct T { pub a: u8 }",
        "#[derive(Serialize)] pub struct T { #[serde(rename(serialize = \"a\", deserialize = \"b\"))] pub a: u8 }",
    ] {
        assert!(struct_fields(source).is_err(), "accepted {source}");
    }
}
